### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by eerzho** [rakutentech/laravel-request-docs#8]
Trying to get property 'id' of non-object
![image](https://user-images.githubusercontent.com/56928699/132200714-39e8a052-7fd8-4721-bb46-931509d62364.png)
Call to a member function hasRole() on null
![image](https://user-images.githubusercontent.com/56928699/132201108-6f3b5e8a-1004-42ff-8c4a-f1f73d0f663b.png)

Hi, I apologize of course, but I could not find a solution to this problem, can you tell me how to fix it

**Comment by kevincobain2000** [comment]
Thanks, for reporting I will confirm.

**Comment by SagarNaliyapara** [comment]
I had similar error on `$this->route('user')->someOperation()` 
```someOperation() on null```

**Comment by SagarNaliyapara** [comment]
I had errors on DI on rules method as well, I'll keep eye on the package 👀 exactly what I want :)

**Comment by gregorip02** [comment]
@eerzho The problem is that it tries to generate a static documentation about a scenario at runtime. `Auth::user()` is null when generating the documentation, so whatever validation rules you add inside your condition will be skipped.

If you are in PHP >= 8 you can use the null safe operator in the following way.

```php
if (Auth::user()?->hasRole(UserRole::ADMIN)) {
  // Do something.
}
```

**Comment by kevincobain2000** [comment]
This should be fixed, I have also added a try catch for rules that fail to parse.

**Comment by SagarNaliyapara** [comment]
@kevincobain2000 I'm still getting errors when it is failed to parse, can we just skip and list all the failed routes so we can manage that manually?

**Comment by kevincobain2000** [comment]
Please retry

**Comment by eerzho** [comment]
@kevincobain2000 Thanks!
